### ISSUE TITLE
Version storage and caching

### ISSUE THREAD

**Issue by SquidDev** [Team-CC-Corp/Grin-Get#5]
Currently the `releases.json` stores a lot more information than we need: urls for downloads, user data, etc... This makes the file much larger than it needs to be and so reading it is slower than need be.

The read data is also not cached meaning methods like `grin.getPackageAPI` take much longer to execute. Consequently there is noticeable lag executing programs which call this method (>0.05 seconds).

**Comment by ElvishJerricco** [comment]
This sounds like a good optimization, but caching would be hard if we want to anticipate the file changing from some other instance of the grin API.

**Comment by SquidDev** [comment]
True. Would caching the file size of the `releases.json` file be enough to determine whether it has changed or not? If it has then you invalidate the version cache for that package.

**Comment by ElvishJerricco** [comment]
I don't think so. It'd be easy enough for the only things that change to be the hash and version numbers, which would result in a file of identical size.

**Comment by SquidDev** [comment]
This appears to no longer be an issue as of af22f85.
